# --- Stage 1: Build ---
FROM golang:1.22 AS builder

WORKDIR /app

# Copia os arquivos de módulo primeiro para aproveitar o cache do Docker
COPY go.mod ./

# Download das dependências
RUN go mod download

# Copia o código-fonte
COPY . .

# Build do binário
RUN CGO_ENABLED=0 GOOS=linux go build -o peer .

# --- Stage 2: Run ---
FROM alpine:latest

WORKDIR /app

# Copia o binário compilado
COPY --from=builder /app/peer .

EXPOSE 8080

# Executa o binário
CMD ["./peer"]
