# --- Stage 1: Build ---
FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build do binário
RUN CGO_ENABLED=0 GOOS=linux go build -o peer .

# --- Stage 2: Run ---
FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/peer .

EXPOSE 8080

CMD ["./peer"]
